"""Initial migration

Revision ID: 920684ee3a4f
Revises: 
Create Date: 2025-10-30 15:51:15.875001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920684ee3a4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('air_quality', sa.Float(), nullable=False),
    sa.Column('water_quality', sa.Float(), nullable=False),
    sa.Column('co2_emissions', sa.Float(), nullable=False),
    sa.Column('incidents', sa.Integer(), nullable=False),
    sa.Column('subscribers', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['port.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('user')
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_name'))

    op.drop_table('port')
    # ### end Alembic commands ###
